import "./globals.css";
import type { Metadata } from "next";
import poppins from "@/lib/helpers/fonts.helper";
import Provider from "@/lib/providers/Provider.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </Provider>
  );
}
